Repository substrate-developer-hub/substrate-developer-hub.github.io, pull requests merged in 2019-10, with the labels that each got.

#263 Add "copy" code button
  website/siteConfig.js
  website/static/css/code-block-buttons.css
  website/static/js/code-block-buttons.js
Labels: A0-pleasereview

#264 Fix Overflow from Footer
  website/core/Footer.js
  website/static/css/custom.css
Labels: A0-pleasereview

#270 Local copy of clipboard.min.js
  website/siteConfig.js
  website/static/js/clipboard.min.js
Labels: A0-pleasereview, A2-insubstantial

#278 Add `getting-started` docs to `next`
  docs/getting-started.md
Labels: A0-pleasereview, T2-Page

#253 Conceptual: SCALE Codec
  docs/conceptual/core/codec.md
Labels: A0-pleasereview, S0-Conceptual, T2-Page

#287 Updated Offchain APIs list
  docs/overview/off-chain-workers.md
  website/versioned_docs/version-1.0/overview/off-chain-workers.md
Labels: A0-pleasereview

#281 Conceptual Doc: Executor
  docs/conceptual/core/executor.md
Labels: A0-pleasereview, S0-Conceptual, T2-Page

#293 Remove Reference Docs, Add Recipes
  website/siteConfig.js
Labels: A0-pleasereview, A2-insubstantial

#292 SubstrateDev Builders List Update
  website/data/users.js
  website/static/img/users/Bifrost.png
  website/static/img/users/Blockdaemon.png
  website/static/img/users/Caelumlabs.png
  website/static/img/users/Daohub.png
  website/static/img/users/Darwinia.png
  website/static/img/users/Dothereum.png
  website/static/img/users/Everstake.png
  website/static/img/users/Gunclear.png
  website/static/img/users/HiveNet.png
  website/static/img/users/Laminar.png
  website/static/img/users/Litentry.png
  website/static/img/users/MixBytes.png
  website/static/img/users/Ngrave.png
  website/static/img/users/Runtime Verification.png
  website/static/img/users/SwarmCity.png
  website/static/img/users/SymbolicSoftware.png
  website/static/img/users/UseTech.png
  website/static/img/users/Validators.png
  website/static/img/users/ValidityLabs.png
  website/static/img/users/WiV.png
  website/static/img/users/dockio.png
Labels: A8-looksgood

#295 Fix capitalization on images
  website/data/users.js
Labels: A2-insubstantial

#297 Fix capitalization
  website/data/users.js
Labels: A2-insubstantial

#294 SRML Conceptual Doc
  docs/assets/srml-arch.png
  docs/conceptual/runtime/srml.md
Labels: A0-pleasereview
