Repository substrate-developer-hub/substrate-developer-hub.github.io, pull requests merged in 2019-09, with the labels that each got.

#202 Add `/presentations/` page to substrate.dev
  website/core/Footer.js
  website/data/videos.js
  website/pages/en/community.js
  website/pages/en/videos.js
  website/siteConfig.js
  website/static/presentations/Consensus in Substrate - Robert Habermeier.pdf
  website/static/presentations/Forkless Upgrades - Shawn Tabrizi.pdf
  website/static/presentations/Intro to Rust - Maciej Hirsz.pdf
Labels: A0-pleasereview

#163 Init runtime metadata documentation
  docs/overview/low-level-data-format.md
  docs/runtime/runtime-metadata.md
  website/sidebars.json
Labels: A0-pleasereview

#230 Integrate Klaro and Google Analytics
  website/core/Footer.js
  website/siteConfig.js
  website/static/css/custom.css
  website/static/js/config.js
  website/static/js/datalayer.js
  website/static/js/klaro.min.js
  website/static/js/load.js
Labels: A0-pleasereview

#242 Update KILT Logo
  website/data/users.js
  website/static/img/users/kiltprotocol_full.png
Labels: A0-pleasereview

#246 Add new Polkadot JS API Tutorial
  docs/getting-started/index.md
  website/pages/en/index.js
  website/pages/en/tutorials.js
  website/pages/en/who/front-end-developer.js
  website/static/img/polkadot-js-api-tutorial.png
  website/static/img/polkadot-js-substrate-tutorial.png
  website/static/img/polkadot-js-tutorial.png
Labels: A0-pleasereview

#244 Add Contribution Guidelines for Substrate Documentation
  CONTRIBUTING.md
  style-guide.md
Labels: A0-pleasereview

#249 Update readme.md
  readme.md
Labels: A0-pleasereview

#251 Fix `who` docs for Contracts
  website/pages/en/who/contract-developer.js
Labels: A0-pleasereview

#252 Move v2.0 Plan to `/next/` docs
  docs/conceptual/core/codec.md
  docs/conceptual/core/consensus.md
  docs/conceptual/core/executor.md
  docs/conceptual/core/networking.md
  docs/conceptual/core/storage.md
  docs/conceptual/index.md
  docs/conceptual/keyring/cryptography.md
  docs/conceptual/keyring/session-keys.md
  docs/conceptual/keyring/subkey.md
  docs/conceptual/node/client.md
  docs/conceptual/node/extrinsics.md
  docs/conceptual/node/light-client.md
  docs/conceptual/node/rpc.md
  docs/conceptual/node/tx-pool.md
  docs/conceptual/runtime/contracts.md
  docs/conceptual/runtime/index.md
  docs/conceptual/runtime/primitives.md
  docs/conceptual/runtime/srml.md
  docs/development/deployment/account-prefix.md
  docs/development/deployment/boot-node.md
  docs/development/deployment/chain-spec.md
  docs/development/deployment/disabling-features.md
  docs/development/front-end/json-rpc.md
  docs/development/front-end/polkadot-js.md
  docs/development/index.md
  docs/development/module/declaration.md
  docs/development/module/errors.md
  docs/development/module/events.md
  docs/development/module/execution.md
  docs/development/module/index.md
  docs/development/module/macros.md
  docs/development/module/origin.md
  docs/development/module/storage.md
  docs/development/module/tests.md
  docs/development/module/traits.md
  docs/development/module/weight.md
  docs/getting-started.md
  docs/getting-started/index.md
  docs/glossary.md
  docs/index.md
  website/sidebars.json
  website/siteConfig.js
Labels: A0-pleasereview

#256 Create a Proof Of Existence Chain Tutorial
  docs/assets/file-hash.png
  docs/assets/forks.png
  docs/assets/front-end-template-balance-transfer.png
  docs/assets/front-end-template.png
  docs/assets/poe-claimed.png
  docs/assets/poe-component.png
  docs/assets/runtime.png
  docs/tutorials/creating-your-first-substrate-chain.md
  docs/tutorials/creating-your-first-substrate-chain/build.md
  docs/tutorials/creating-your-first-substrate-chain/index.md
  docs/tutorials/creating-your-first-substrate-chain/interact.md
  docs/tutorials/creating-your-first-substrate-chain/learn.md
  docs/tutorials/creating-your-first-substrate-chain/setup.md
  docs/tutorials/creating-your-first-substrate-chain/test.md
  website/sidebars.json
Labels: A0-pleasereview, S1 - Development, T4-Tutorial

#255 Conceptual: Substrate Storage
  docs/conceptual/core/storage.md
  docs/development/module/storage.md
Labels: A0-pleasereview, S0-Conceptual, T2-Page

#261 Add (configurable) Hacktoberfest blast
  website/core/Footer.js
  website/siteConfig.js
  website/static/img/hacktoberfest-blast-bg.png
Labels: A0-pleasereview
