Repository substrate-developer-hub/substrate-developer-hub.github.io, pull requests merged in 2019-08, with the labels that each got.

#191 Substrate front-end tutorial
  docs/assets/tutorials/substrate-front-end/part-2-1.jpg
  docs/assets/tutorials/substrate-front-end/part-2-2.jpg
  docs/assets/tutorials/substrate-front-end/part-2-3.jpg
  docs/assets/tutorials/substrate-front-end/part-3-1.jpg
  docs/assets/tutorials/substrate-front-end/part-4-1.jpg
  docs/assets/tutorials/substrate-front-end/part-4-2-auth.jpg
  docs/assets/tutorials/substrate-front-end/part-4-2-external-balances.jpg
  docs/assets/tutorials/substrate-front-end/part-4-3.jpg
  docs/tutorials/substrate-front-end/index.md
  docs/tutorials/substrate-front-end/part-1-connect-to-a-node.md
  docs/tutorials/substrate-front-end/part-2-query-balances.md
  docs/tutorials/substrate-front-end/part-3-transfer-funds.md
  docs/tutorials/substrate-front-end/part-4-use-external-accounts.md
  website/pages/en/tutorials.js
  website/sidebars.json
  website/static/img/polkadot-js-tutorial.png
Labels: A0-pleasereview

#207 Fix minor typos in contracts overview.
  docs/contracts/index.md
Labels: A2-insubstantial

#209 Simplify part-4-* for users without extension
  docs/tutorials/substrate-front-end/part-4-use-external-accounts.md
Labels: A2-insubstantial

#211 Publish link to verifiable credentials workshops
  website/pages/en/tutorials.js
Labels: A2-insubstantial

#187 Revise Session Certificate Page
  docs/contracts/index.md
  docs/overview/index.md
  docs/overview/session-keys.md
Labels: A0-pleasereview, T2-Page

#212 Add page for recent events
  website/pages/en/community.js
  website/static/css/custom.css
Labels: A3-inprogress

#223 Open "users" on a new tab
  website/pages/en/index.js
  website/pages/en/users.js
Labels: A0-pleasereview
